apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sandbox-emcla-kf9a1
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: FIXME
  path: "./FIXME"
  prune: true
  timeout: 1m
  postBuild:
    substitute:
      capability_id: sandbox-emcla-kf9a1
      capability_data_namespace: capability-data