apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../
helmCharts:
  - name: chart
    releaseName: capability
    version: 1.0.0
    valuesInline:
      capability:
        id: sandbox-emcla-kf9a1