apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.capability.id }}-admission-resources
  namespace: {{ .Values.capability.id }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
spec:
  limits:
  - default:
      cpu: "1"
      memory: 256Mi
    defaultRequest:
      cpu: 20m
      memory: 64Mi
    max:
      cpu: "4"
      memory: 16Gi
    type: Container
  - max:
      cpu: "4"
      memory: 16Gi
    type: Pod
