apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.capability.id }}-sso-group
  namespace: {{ .Values.capability.id }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.capability.id }}-capability-access
subjects:
- kind: ServiceAccount
  name: {{ .Values.capability.id }}
  namespace: {{ .Values.capabilityDataNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.capability.id }}-sa
  namespace: {{ .Values.capability.id }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.capability.id }}-capability-access
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{ .Values.capability.id }}
