apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ .Values.capability.id }}-token
  namespace: {{ .Values.capabilityDataNamespace }}
  labels:
    {{- include "commonLabels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.capability.id }}