---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sandbox-emcla-kf9a1
namePrefix: ssu-sandbox-emcla-kf9a1-
resources:
  - ../../base
# patches:
#   - target:
#       kind: RoleBinding
#     patch: |-
#       - op: replace
#         path: /roleRef/name
#         value: sandbox-emcla-kf9a1

replacements:
  - source:
      value: REPLACEME
    targets:
      - select:
          kind: .*