apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${capability_id}-sso-group
  namespace: ${capability_id}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ${capability_id}-capability-access
subjects:
- kind: ServiceAccount
  name: ${capability_id}
  namespace: ${capability_data_namespace}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${capability_id}-sa
  namespace: ${capability_id}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ${capability_id}-capability-access
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: ${capability_id}