apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: ${capability_id}-token
  namespace: ${capability_data_namespace}
  annotations:
    kubernetes.io/service-account.name: ${capability_id}