name: ssu-k8s build

on:
  push:
    branches:
      - "main"
    paths:
      - 'cmds/**'
      - 'core/**'
      - 'feats/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:
    inputs:
      deploy:
        default: false
        required: false
        type: boolean
        description: "Trigger build"

jobs:
  deploy:
    name:  '01 - Linux'
    runs-on: [ubuntu-22.04]
    strategy:
      matrix:
        arch: ['x86_64']
    defaults:
      run:
        shell: bash
        #working-directory: /tmp
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: dfdsdk/ssu-k8s:latest